baseURL: "https://stumbleupon.blog/"
languageCode: en-us
title: StumbleUpon.blog
theme: etch

enableInlineShortcodes: true
pygmentsCodeFences: true
pygmentsUseClasses: true

params: 
  description: Your site description
  copyright: Copyright © 2023 Blog Owner
  highlight: true


menu:
  main:
    - identifier: posts
      name: posts
      title: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      title: tags
      url: /tags/
      weight: 20
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 30

permalinks:
  posts: '/:title/'

markup:
  goldmark:
    renderer:
      unsafe: true

  